### ISSUE TITLE
I just mined 98000000 odn

### ISSUE THREAD

**Issue by wtf1111** [obsidianproject/Obsidian-Qt#10]
I just downloaded the wallet and i mined 98 million odn...

**Comment by wtf1111** [comment]
![untitled](https://user-images.githubusercontent.com/31492802/29899274-6268e93a-8db8-11e7-9358-8cd75526c9f4.png)

**Comment by Raffail** [comment]
Me too :-) But this amount went to Proof-of-stake balance after 51 confirmations, not to available ODN. So sad. I started to choose a castle, small island and yacht...

**Comment by Jimmar** [comment]
you are rich !!!
jk, you are on the wrong chain, check slack

**Comment by suspended** [comment]
I am guessing you didn't wait for the blochchain to sync before mining
