### ISSUE TITLE
Install missing libraries on Ubuntu 16.04.

### ISSUE THREAD

**Issue by netsfx** [obsidianproject/Obsidian-Qt#14]
This tread shows how to install missing dependencies on Ubuntu 16.04. (only that version).

**Comment by netsfx** [comment]
thanks to via @fatima: (modified)
------------------------
Obsidian
1. Install prerequisites for running QT wallet on Ubuntu
sudo apt-get install build-essential autoconf libtool pkg-config libboost-all-dev libssl-dev libevent-dev libsodium-dev
2. sudo apt install libminiupnpc-dev
3. Install older version of berkley DB libs
wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
tar xzvf db-4.8.30.NC.tar.gz
cd db-4.8.30.NC/build_unix/
../dist/configure --enable-cxx
make
sudo make install
4. Create symlink to required lib
cd /usr/lib
sudo ln -s /usr/local/BerkeleyDB.4.8/lib/libdb_cxx-4.8.so libdb_cxx-4.8.so
5. Make executable and launch Obsidian-Qt
chmod a+x Obsidian-Qt
./Obsidian-Qt
6. only if it's not syncing after a minute, in wallet debug window:
addnode 104.45.21.229 add
(that might fix dns problems)
7.) to start mining (available till block 12500):
setgenerate true -1

**Comment by circledot** [comment]
Although these instructions seem to work on ubuntu derivatives (e.g. mint), I would much prefer a distro independent self-contained executable.

Thanks
