### ISSUE TITLE
Windows x64 - socket recv error 10054 & socket send error 10053

### ISSUE THREAD

**Issue by NeilChill** [obsidianproject/Obsidian-Qt#18]
Windows x64
Multiple coinbase timestamp failed errors
sync's correctly then occasional socket recv error 10054 and loss of sync until reopening of wallet

**Comment by petermcclory** [comment]
Please backup your wallet.dat and use the latest version of the Windows wallet. Thank you.

**Comment by TechniumUnlimited** [comment]
More info on this?

**Comment by netsfx** [comment]
that's not a bug.
