### ISSUE TITLE
File -> Export doesn't seem to be doing anything

### ISSUE THREAD

**Issue by Jimmar** [obsidianproject/Obsidian-Qt#20]
`File -> backup wallet` seems to export the `wallet.dat` file but the `File -> Export` doesn't seem to be doing anything

**Comment by netsfx** [comment]
works on macOS

**Comment by Jimmar** [comment]
on windows export doesn't seem to be doing anything
so is export for mac and backup wallet for windows ?

**Comment by petermcclory** [comment]
This is fixed on the latest updated wallets.
