### ISSUE TITLE
macOS wallet crashes, error details contain: libdb_cxx-4.8.dylib

### ISSUE THREAD

**Issue by aubergemediale** [obsidianproject/Obsidian-Qt#24]
Process:               Obsidian-Qt [10011]
Path:                  /Volumes/VOLUME/Obsidian-Qt.app/Contents/MacOS/Obsidian-Qt
Identifier:            co.obsidian.Obsidian-Qt
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Obsidian-Qt [10011]
User ID:               501
Date/Time:             2017-09-10 14:24:03.145 -0400
OS Version:            Mac OS X 10.11.6 (15G1108)
Report Version:        11
Anonymous UUID:        235640C8-1117-FA98-F991-5C2C45979F84
Sleep/Wake UUID:       B10DC31C-B053-4210-BB31-AE9DAE997CE3
Time Awake Since Boot: 1800000 seconds
Time Since Wake:       3600 seconds
System Integrity Protection: enabled
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
Dyld Error Message:
  Symbol not found: _clock_gettime
  Referenced from: /Volumes/VOLUME/Obsidian-Qt.app/Contents/MacOS/../Frameworks/libdb_cxx-4.8.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dyld                            0x00007fff6d57b075 dyld_fatal_error + 1
1   dyld                            0x00007fff6d57e094 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 139
2   libdyld.dylib                   0x00007fff89ce8262 dyld_stub_binder + 282
3   ???                             0x0000000105e86008 0 + 4394082312
4   libdb_cxx-4.8.dylib             0x0000000105e5d028 __os_unique_id + 67
5   libdb_cxx-4.8.dylib             0x0000000105e35978 __env_attach + 1084
6   libdb_cxx-4.8.dylib             0x0000000105e332c7 __env_attach_regions + 225
7   libdb_cxx-4.8.dylib             0x0000000105e32c36 __env_open + 205
8   libdb_cxx-4.8.dylib             0x0000000105d6c358 DbEnv::open(char const*, unsigned int, int) + 80
9   co.obsidian.Obsidian-Qt         0x00000001055c3d95 CDBEnv::Open(boost::filesystem::path) + 805
10  co.obsidian.Obsidian-Qt         0x000000010558e211 AppInit2(boost::thread_group&) + 8753
11  co.obsidian.Obsidian-Qt         0x000000010542fbce main + 4846
12  libdyld.dylib                   0x00007fff89cea5ad start + 1
Thread 1:
0   libsystem_kernel.dylib          0x00007fff98cd85e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff90a7b578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff90a79341 start_wqthread + 13
Thread 2:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib          0x00007fff98cd8efa kevent_qos + 10
1   libdispatch.dylib               0x00007fff93758165 _dispatch_mgr_invoke + 216
2   libdispatch.dylib               0x00007fff93757dcd _dispatch_mgr_thread + 52
Thread 3:: Dispatch queue: NSCGSDisableUpdates
0   libsystem_kernel.dylib          0x00007fff98cd1f72 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff98cd13b3 mach_msg + 55
2   com.apple.CoreGraphics          0x00007fff9aa09ee0 _CGSReenableUpdateForConnection + 92
3   com.apple.CoreGraphics          0x00007fff9aa09bbd CGSReenableUpdateToken + 532
4   libdispatch.dylib               0x00007fff9375d93d _dispatch_call_block_and_release + 12
5   libdispatch.dylib               0x00007fff9375240b _dispatch_client_callout + 8
6   libdispatch.dylib               0x00007fff9375703b _dispatch_queue_drain + 754
7   libdispatch.dylib               0x00007fff9375d707 _dispatch_queue_invoke + 549
8   libdispatch.dylib               0x00007fff9375240b _dispatch_client_callout + 8
9   libdispatch.dylib               0x00007fff9375629b _dispatch_root_queue_drain + 1890
10  libdispatch.dylib               0x00007fff93755b00 _dispatch_worker_thread3 + 91
11  libsystem_pthread.dylib         0x00007fff90a7b4de _pthread_wqthread + 1129
12  libsystem_pthread.dylib         0x00007fff90a79341 start_wqthread + 13
Thread 4:
0   libsystem_kernel.dylib          0x00007fff98cd85e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff90a7b578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff90a79341 start_wqthread + 13
Thread 5:
0   libsystem_kernel.dylib          0x00007fff98cd85e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff90a7b578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff90a79341 start_wqthread + 13
Thread 6:
0   libsystem_kernel.dylib          0x00007fff98cd85e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff90a7b578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff90a79341 start_wqthread + 13
Thread 7:
0   libsystem_kernel.dylib          0x00007fff98cd85e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff90a7b578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff90a79341 start_wqthread + 13
Thread 8:
0   libsystem_kernel.dylib          0x00007fff98cd85e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff90a7b578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff90a79341 start_wqthread + 13
Thread 9:
0   libsystem_kernel.dylib          0x00007fff98cd85e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib         0x00007fff90a7b578 _pthread_wqthread + 1283
2   libsystem_pthread.dylib         0x00007fff90a79341 start_wqthread + 13
Thread 10:
Thread 11:: com.apple.CFSocket.private
0   libsystem_kernel.dylib          0x00007fff98cd807a __select + 10
1   com.apple.CoreFoundation        0x00007fff9103045a __CFSocketManager + 762
2   libsystem_pthread.dylib         0x00007fff90a7b99d _pthread_body + 131
3   libsystem_pthread.dylib         0x00007fff90a7b91a _pthread_start + 168
4   libsystem_pthread.dylib         0x00007fff90a79351 thread_start + 13
Thread 12:: com.apple.NSEventThread
0   libsystem_kernel.dylib          0x00007fff98cd1f72 mach_msg_trap + 10
1   libsystem_kernel.dylib          0x00007fff98cd13b3 mach_msg + 55
2   com.apple.CoreFoundation        0x00007fff90ff3124 __CFRunLoopServiceMachPort + 212
3   com.apple.CoreFoundation        0x00007fff90ff25ec __CFRunLoopRun + 1356
4   com.apple.CoreFoundation        0x00007fff90ff1e38 CFRunLoopRunSpecific + 296
5   com.apple.AppKit                0x00007fff8ff76d95 _NSEventThread + 149
6   libsystem_pthread.dylib         0x00007fff90a7b99d _pthread_body + 131
7   libsystem_pthread.dylib         0x00007fff90a7b91a _pthread_start + 168
8   libsystem_pthread.dylib         0x00007fff90a79351 thread_start + 13
Thread 13:: QThread
0   libsystem_kernel.dylib          0x00007fff98cd92a2 poll + 10
1   org.qt-project.QtCore           0x0000000106cbf380 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 544
2   org.qt-project.QtCore           0x0000000106cc0845 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 885
3   org.qt-project.QtCore           0x0000000106c66631 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 401
4   org.qt-project.QtCore           0x0000000106a9f19e QThread::exec() + 110
5   org.qt-project.QtCore           0x0000000106aa2e7f 0x106a77000 + 179839
6   libsystem_pthread.dylib         0x00007fff90a7b99d _pthread_body + 131
7   libsystem_pthread.dylib         0x00007fff90a7b91a _pthread_start + 168
8   libsystem_pthread.dylib         0x00007fff90a79351 thread_start + 13
Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00007fff6d5b4290  rbx: 0x00007fbf2cc3a580  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x00007fff6d5b4400  rsi: 0x0000000000000000  rbp: 0x00007fff5a7f1210  rsp: 0x00007fff5a7f11f8
   r8: 0x00007fff6d59d04c   r9: 0x0000000000000000  r10: 0x00007fff6d5a0462  r11: 0x00007fff6d5b4400
  r12: 0x0000000000000000  r13: 0x0000000000000065  r14: 0x00007fff6d5b4400  r15: 0x00007fff5a7f16f8
  rip: 0x00007fff6d57b075  rfl: 0x0000000000000246  cr2: 0x000000010714f000
  
Logical CPU:     4
Error Code:      0x00000000
Trap Number:     3
Binary Images:
       0x10540d000 -        0x1059a6ffb +co.obsidian.Obsidian-Qt (0) <C7F1572A-A08E-364E-91E6-65E06462A003> /Volumes/VOLUME/Obsidian-Qt.app/Contents/MacOS/Obsidian-Qt
       0x105af0000 -        0x105af7ffb +libqrencode.3.dylib (0) <BC6DB033-79F3-35BA-BB57-04ABC7C302C3> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libqrencode.3.dylib
       0x105b00000 -        0x105b08ff7 +libminiupnpc.16.dylib (0) <1A189147-0AF2-3ED3-A35A-164FB457E38F> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x105b0d000 -        0x105b56ff7 +libssl.1.0.0.dylib (0) <0D0BED58-658B-37A4-A9EA-C35BA07F973A> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x105b79000 -        0x105cfc437 +libcrypto.1.0.0.dylib (0) <777E96D9-D804-3754-A100-B4623CF5EA05> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x105d65000 -        0x105e85ff7 +libdb_cxx-4.8.dylib (0) <91F98B38-7870-309E-B860-479469F5D3DB> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x105eb1000 -        0x105eb3fff +libboost_system-mt.dylib (0) <ED86ABC8-84C1-3508-9362-6E2AB9295F0D> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libboost_system-mt.dylib
       0x105ebb000 -        0x105ec9ff7 +libboost_filesystem-mt.dylib (0) <85C65F2C-FCB4-38F0-9CD4-431BF243B211> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libboost_filesystem-mt.dylib
       0x105ed4000 -        0x105f08fff +libboost_program_options-mt.dylib (0) <2E935CBA-E26F-3563-82DD-55B36E9A5A9A> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x105f2a000 -        0x105f36ff7 +libboost_thread-mt.dylib (0) <A6B93F03-1583-326B-A986-DAC5A729045A> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x105f41000 -        0x105f9bfe3 +libsodium.18.dylib (0) <54252F6C-8AC6-3F7D-925A-42665AAE3FBA> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libsodium.18.dylib
       0x105fa9000 -        0x10640efff +org.qt-project.QtWidgets (5.9 - 5.9.1) <A4CFEC5D-5488-32B6-B7C8-A6A90493598B> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10656a000 -        0x10656afe7 +cl_kernels (???) <F4FB7712-1766-4C21-BCC3-390C8A78594D> cl_kernels
       0x10656f000 -        0x106980ff7 +org.qt-project.QtGui (5.9 - 5.9.1) <425B6D3F-7724-348D-9827-43F97508414B> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x106a77000 -        0x106f50fff +org.qt-project.QtCore (5.9 - 5.9.1) <81B162CC-7629-337B-AC44-45B7ABD609B6> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x107006000 -        0x10710aff7 +org.qt-project.QtNetwork (5.9 - 5.9.1) <D25A7C0E-5BDC-3F19-B440-B915F9F67BB3> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x107150000 -        0x107154fff  com.apple.agl (3.3.1 - AGL-3.3.1) <4E401980-0F4F-33E2-A0CF-8C7CCF375F24> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
       0x107162000 -        0x107172ffb +libz.1.dylib (0) <59C83AE6-76F4-3E33-8DA8-B1C7AFA4E20E> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/libz.1.dylib
       0x109d53000 -        0x109ea1fff +libqcocoa.dylib (0) <C3142FD2-18F6-3B72-A20D-9C3CC2048576> /Volumes/VOLUME/Obsidian-Qt.app/Contents/PlugIns/platforms/libqcocoa.dylib
       0x109ee6000 -        0x109f12fff +org.qt-project.QtPrintSupport (5.9 - 5.9.1) <0598E3BB-24DF-3BE8-B49D-27EE2F30DA42> /Volumes/VOLUME/Obsidian-Qt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x10b425000 -        0x10b42bff7 +libqgif.dylib (0) <FA1193A8-3C85-3BE7-BE01-31370E2664E8> /Volumes/VOLUME/Obsidian-Qt.app/Contents/PlugIns/imageformats/libqgif.dylib
       0x10cac0000 -        0x10cac7fff +libqicns.dylib (0) <D9ECD8F6-0F52-3DBC-A245-098856439151> /Volumes/VOLUME/Obsidian-Qt.app/Contents/PlugIns/imageformats/libqicns.dylib
       0x10cacc000 -        0x10cad1fff +libqico.dylib (0) <2862D26F-8BBE-34BB-804A-0CA33E6C6493> /Volumes/VOLUME/Obsidian-Qt.app/Contents/PlugIns/imageformats/libqico.dylib
       0x10cad6000 -        0x10cb10fff +libqjpeg.dylib (0) <FA1BB524-36D4-35A5-8659-BD2F978238B1> /Volumes/VOLUME/Obsidian-Qt.app/Contents/PlugIns/imageformats/libqjpeg.dylib
       0x10cb16000 -        0x10cb1aff7 +libqmacjp2.dylib (0) <46E82B09-032C-33CC-890E-1AC0941370A5> /Volumes/VOLUME/Obsidian-Qt.app/Contents/PlugIns/imageformats/libqmacjp2.dylib
       0x10cb1e000 -        0x10cb22fff +libqsvg.dylib (0) <F85278D6-80...

**Comment by aubergemediale** [comment]
Two people fixed this by upgrading to macOS 10.12...

**Comment by alexanderkoumis** [comment]
Would be nice to put a little effort into making it compatible with earlier versions of macOS (I'm running 10.11 and can't upgrade for a reason I'd rather not go into).

**Comment by netsfx** [comment]
yes, we will!

**Comment by petermcclory** [comment]
This is fixed by updating macOS to the latest version using Apple's standard Updates for the operating system. Current version is macOS Sierra 10.12.6

**Comment by alexanderkoumis** [comment]
Hi @petermcclory, any plans to make it compatible with OSX 10.11? There are some users that can't upgrade to Sierra for various reasons.

**Comment by netsfx** [comment]
try version 1.0.0.7
