### ISSUE TITLE
Wallet crashing In Mac

### ISSUE THREAD

**Issue by Anchit05** [obsidianproject/Obsidian-Qt#29]
After downloading the wallet. While opening it's crashing again and again. Not able to complete the process of getting my coins into my wallet. Please have a look into this.

**Comment by alexanderkoumis** [comment]
You are probably running into this: https://github.com/obsidianproject/Obsidian-Qt/issues/24

If you can, upgrade your OSX version

**Comment by netsfx** [comment]
see #24
