### ISSUE TITLE
Still not syncing no matter what

### ISSUE THREAD

**Issue by bcubedla** [obsidianproject/Obsidian-Qt#31]
I have windows 10. I have downloaded the most recent version and I still get no syncing and not even a connection. I have left on for several hours and still nothing. 

I have done all of the addnodes that were in the slack channel. I created the conf file like in the video. It doesn't even end up connecting at all. I have even taken down my firewalls. What do?

**Comment by ghostfish25** [comment]
Same here, I am on Windows 10 using the Windows wallet versionv1.0.0.6-g32a928e.  I've been trying to synchronize with the network for 2 days and it never moved from 2 weeks behind.  In the logs I am seeing a lot of 'ProcessBlock: ORPHAN BLOCK';, and 'check proof-of-stake fails'

**Comment by netsfx** [comment]
perhaps you are stuck on the wrong chain. Can you backup your wallet, delete the ObsidianQt folder in %appdata%/roaming and then run the wallet again? I'm also running it on Wondows 10 with no addnode required and any other issues!

**Comment by bcubedla** [comment]
I deleted everything and then reinstalled and it's still not syncing.

**Comment by petermcclory** [comment]
Have you synced now?

**Comment by netsfx** [comment]
https://github.com/obsidianproject/Obsidian-Qt/wiki/Sync-the-Obsidian-Qt-Wallet

**Comment by TeisH** [comment]
Have you tried changing your firewall setting on your router ? The missing sync can be due to port restrictions settings found on your routers config page ?

**Comment by bcubedla** [comment]
I'm in an office that I rent and cannot change the router. I will try when I get home.

**Comment by bcubedla** [comment]
I deleted the .6 version and the appdata as well. I have downloaded the newest version. Do I need to do the addnode like in the previous versions? What about the conf file. I have quite a bit of coins so I want to get them in a wallet quickly.

**Comment by TeisH** [comment]
Hi bcubedla

Have you looked at the guide previously posted ? 
https://github.com/obsidianproject/Obsidian-Qt/wiki/Sync-the-Obsidian-Qt-Wallet

Try to either enable UPnP/ or enable port forwarding to port 56660 on your router. These settings are found your routers config page. To learn more about how to change the setting: Go to Google and enter "your router name" + "firewall setting"

**Comment by bcubedla** [comment]
UPnP was already enabled. I went in and configured port forwarding as well. I used the IP address of my computer. Do I need to use the IP address of my router instead of my comp? 

Still wasn't working. 

Then did the addnode again as in your post and still nothing. 

Any other options? I'm in Mexico, does that have anything to do with it?

**Comment by bcubedla** [comment]
I have tried this at both my office and my home and nothing. I may just have to have my Obsidian coins sent to an exchange once it hits one. 

I've spent hours on this thing and I seem to be the only one that is not working.

**Comment by TeisH** [comment]
Hi bcubedla

Ok, try go to you routers setting and see if there is a general setting for "IPv4 Firewall Protection". 
Many routers have a predefined security levels defined as: None, Low, Medium and High.

If you have this possibility, try to set your firewall to low security. Normally this would imply that only 
basic control is inforced on your incoming connections. (Please check online if this is also the case for your router)

Now if you are able to sync now, you will know that it is your firewall setting that is causing the problem and you did not setup your forwarding correctly. 

If it still doesn't work I think the problem is elsewhere. 

Remember to reset your firewall setting to the original state once you are done.

**Comment by bcubedla** [comment]
still nothing. I disabled everything on my router. I'm going to get an account with digital ocean and try to run in there.

**Comment by bcubedla** [comment]
Is there anything I can do? I don't think that it has anything to do with my router or firewall. Is it better to set up ubuntu on my comp or digital ocean and use from there?

**Comment by ghostfish25** [comment]
I deleted the entire %appdata% folder. That helped me.
