### ISSUE TITLE
Unabe to lauch wallet on MAC

### ISSUE THREAD

**Issue by BitFlippa** [obsidianproject/Obsidian-Qt#38]
Process:               Obsidian-Qt [72165]
Path:                  /Volumes/VOLUME/Obsidian-Qt.app/Contents/MacOS/Obsidian-Qt
Identifier:            co.obsidian.Obsidian-Qt
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Obsidian-Qt [72165]
User ID:               501

Date/Time:             2017-09-23 14:10:41.768 -0400
OS Version:            Mac OS X 10.11.1 (15B42)
Report Version:        11
Anonymous UUID:        7D388F2E-C4C3-CAA4-7869-B8E7B83ACEE5

Sleep/Wake UUID:       BA32C0A8-9FD3-4D10-B3AC-C0BDEB177A51

Time Awake Since Boot: 440000 seconds
Time Since Wake:       100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Dyld Error Message:
  Symbol not found: _clock_gettime
  Referenced from: /Volumes/VOLUME/Obsidian-Qt.app/Contents/MacOS/../Frameworks/libdb_cxx-4.8.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by alexanderkoumis** [comment]
See issue #24

**Comment by netsfx** [comment]
try new version 1.0.0.7

**Comment by alexanderkoumis** [comment]
@netsfx Getting same error:
```
Process:               Obsidian-Qt [25845]
Path:                  /Volumes/VOLUME/Obsidian-Qt.app/Contents/MacOS/Obsidian-Qt
Identifier:            co.obsidian.Obsidian-Qt
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Obsidian-Qt [25845]
User ID:               501

Date/Time:             2017-09-24 19:24:01.332 -0700
OS Version:            Mac OS X 10.11.6 (15G1611)
Report Version:        11
Anonymous UUID:        80D485F2-D086-06A8-466E-E9EAD38715D0

Sleep/Wake UUID:       A284169C-9FD9-4474-B099-281121A3E819

Time Awake Since Boot: 41000 seconds
Time Since Wake:       16000 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Dyld Error Message:
  Symbol not found: _clock_gettime
  Referenced from: /Volumes/VOLUME/Obsidian-Qt.app/Contents/MacOS/../Frameworks/libdb_cxx-4.8.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dyld                          	0x00007fff6fb77075 dyld_fatal_error + 1
1   dyld                          	0x00007fff6fb7a094 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 139
2   libdyld.dylib                 	0x00007fff89bab262 dyld_stub_binder + 282
3   ???                           	0x00000001050af008 0 + 4379570184
4   libdb_cxx-4.8.dylib           	0x0000000105086028 __os_unique_id + 67
5   libdb_cxx-4.8.dylib           	0x000000010505e978 __env_attach + 1084
```

**Comment by netsfx** [comment]
can you download and try again?

**Comment by alexanderkoumis** [comment]
@netsfx 10.0.0.7a works! Thanks so much for fixing this.
