### ISSUE TITLE
Having trouble......not tech. Savy at all...

### ISSUE THREAD

**Issue by mistvisions** [obsidianproject/Obsidian-Qt#39]
Where can I find a video explaining how to set up wallet.It seems like a lot of members are in a similar situation. I hope that an easier way is in the future to get the wallet up and running thank you...

**Comment by netsfx** [comment]
Hello,

if you are a noob you best join our slack!

https://join.slack.com/t/obsidianproject/shared_invite/MjMyMzgyMTY5NjMyLTE1MDM5ODM2NTQtMzNlM2NlNTkwMg
