### ISSUE TITLE
Windows defender finds Trojan BitRep.A in Windows 1.0.0.7-1 release.

### ISSUE THREAD

**Issue by Mentar** [obsidianproject/Obsidian-Qt#40]
Hello,

Like the title states. Windows defender finds Trojan BitRep.A in Windows 1.0.0.7-1 release. 

On Slack people say it is an false positive. This could be, but for the general acceptance of the wallet and the coin. I think it is important to make sure these things don't occur. False positive or not. 

Regards, 
Mentar

**Comment by netsfx** [comment]
hmm, that is strange! What change could have caused that...? Ok we need to check, yes, use v1.0.0.6 in case of doubt!
If anyone has more details (e.g. what OS, what exactly the anti-virus claims), that would be helpful!

**Comment by netsfx** [comment]
Kapersky names it 'Trojan.Win32.IRCbot.awld'

**Comment by netsfx** [comment]
v1.0.0.7 is pulled until it's clear what caused that behavior.

**Comment by netsfx** [comment]
candidate for the cause is this addition:
vSeeds.push_back(CDNSSeedData("Seednode4", "seed1.obsidianplatform.com:8080"));
maybe it's port 8080 which raises the false alert

**Comment by netsfx** [comment]
yup, port 8080 is a bot also used by  bots, which triggers the heuristic in the AV. We'll switch to another port then, so that we don't get false-positives here!
