### ISSUE TITLE
Unable to unlock wallet forever with -1 parameter

### ISSUE THREAD

**Issue by Manbearpixel** [obsidianproject/Obsidian-Qt#41]
Running Obsidiand on a headless version of Ubuntu 16.04 on a VPS...

I was able to setup last night and receive transactions, but when running:
`obsidiand walletpassphrase SECRET123 -1` and verifying my staking info with `obsidiand getstakinginfo` the staking flag returns `false`. However, when I pass an actual integer like `60` and check my staking info again, it is set to `true`. I feel like this is a bug.

**Comment by netsfx** [comment]
I think -1 is wrong! I was more successful with a high number, like 600000. Had no time to look in the code to lookup the right value for 'permanently'!

**Comment by Manbearpixel** [comment]
Yeah, I assumed it was weird. I was going off of the documentation I found so far to run Obsidiand headless:
https://github.com/obsidianproject/Obsidian-Qt/wiki/Staking-on-remote-Ubuntu-machine-(headless-(=without-wallet-UI))

**Comment by Manbearpixel** [comment]
So setting it to 600,000 does that mean you would need to unlock it once every ~6 days? Maybe I should setup a cron job to unlock the wallet every day haha. I'd hate to leave this running and not be staking accidentally

**Comment by netsfx** [comment]
sorry my bad!

**Comment by netsfx** [comment]
hmm, we need to read the parser

**Comment by netsfx** [comment]
https://www.reddit.com/r/reddCoin/comments/2ceze7/posv_time_to_enable_staking/
look here, they use 9999999

**Comment by netsfx** [comment]
updated wiki article with 9999999!

**Comment by netsfx** [comment]
if you report that that works I'll close the issue!

**Comment by Manbearpixel** [comment]
@netsfx Is that the fix? Haha, maybe we can have it as a feature one day though? `-1` seems handy to not have to unlock it again in 9,999,999 seconds 😆

**Comment by Manbearpixel** [comment]
Now it isn't staking at all, I tried 60 - 9999999

**Comment by Manbearpixel** [comment]
All working now, issue can be closed. Didn't realize my balance needs to be reconfirmed 100 times after sending/receiving ODN :)

**Comment by netsfx** [comment]
wonderful!!! :-)
