### ISSUE TITLE
Staking instructions use -1 vs 9999999

### ISSUE THREAD

**Issue by lestshad** [obsidianproject/Obsidian-Qt#44]
On this page, the staking instructions halfway down the page show to use a -1 instead of 9999999 for the staking time: https://github.com/obsidianproject/Obsidian-Qt/wiki/Staking-on-remote-Ubuntu-machine-(headless-(=without-wallet-UI))

This is causing users confusion and having the staking not work correctly. Please change -1 to 99999999 in this documentation on the wiki.

**Comment by netsfx** [comment]
@lestshad , are you not able to edit the wiki...? Maybe we have invalid permission settings?

**Comment by netsfx** [comment]
@lestshad updated wiki to 9999999!
