### ISSUE TITLE
Wallet Encryption Setup -- Add Confirm Password

### ISSUE THREAD

**Issue by Manbearpixel** [obsidianproject/Obsidian-Qt#47]
As a user, I should be prompted to confirm my encryption password when encrypting my wallet to ensure the password I enter is correct and has not been mistyped. This adds an additional step to encrypt the wallet, but should help avoid a mistake as I have to enter it twice to confirm my password.

Brought up by user::ScottP on Slack.

#### Feature Scenario
```
Feature: Password Confirmation for Wallet Encryption
  An user of the Obsidian-QT Wallet should be able to
  encrypt their wallet with a password and a confirmation
  password to ensure the password is correct.

  Scenario: User can confirm encryption password when setting up
    Given I have started my Obsidian-QT Wallet
    When  I decide to encrypt my wallet with a password
    Then  I should see a password prompt screen
    And   I should be required to confirm the password I entered to ensure validity
```

**Comment by netsfx** [comment]
thank you for describing this as a user story, but won't fix for now.
