### ISSUE TITLE
contract

### ISSUE THREAD

**Issue by ricklap** [obsidianproject/Obsidian-Qt#51]
I purchased ODN as an ICO and was thinking about adding it to my "myetherwallet" so I can watch all of the ICO's in one place.  Is there a contract address i can use?

**Comment by netsfx** [comment]
hello, Obsidian is not a so-called ERC20-token - it's a coin like Bitcoin. You can use ODN with the wallets here:
https://github.com/obsidianproject/Obsidian-Qt/releases
That's good id you want to use staking, i.e. get an interest on your balance and support the Obsidian network.

Or, you create a ODN funding address at Cryptopia or hitbtc and send the tokens to that address.

It's not compatible with 'myetehrwallet'.

Thank you for your support!
