### ISSUE TITLE
running obsidiand on a vps

### ISSUE THREAD

**Issue by bereska** [obsidianproject/Obsidian-Qt#53]
first of all THANKS for the great tutorial 'Setting up a VPS to stake your Obsidian! ~@Pixxl'
i just launched my odn node, bought some odn and started staking. All looks good for now.
However I've noticed that `obsidian -daemon` stops after reboot so I have to restart it and open wallet for staking manually again.
Is there a way to automate this without exposing password too much?
thank you

**Comment by Manbearpixel** [comment]
You can setup a `CRON` job to run periodically or a `systemd` to execute a command on boot.

https://askubuntu.com/questions/2368/how-do-i-set-up-a-cron-job

https://askubuntu.com/questions/919054/how-do-i-run-a-single-command-at-startup-using-systemd

**Comment by bereska** [comment]
thank you, Manbearpixel, but the problem is that the password will be saved on the script file on the disk posing even greater security risk. As a solution I am thinking of encrypting the vps disk. Hopefully, this won't mess up staking. What do you think?

**Comment by Manbearpixel** [comment]
It shouldn't! But as always I recommend having a backup of your wallet.dat and/or the private key to your address. 

Let me know if all goes well! Would like to recommend the best methods of security :)
