### ISSUE TITLE
Provide staticaly linked linux binarys

### ISSUE THREAD

**Issue by Hein-Bloed** [obsidianproject/Obsidian-Qt#54]
It would be a lot easier to use the linux binarys if there were staticaly linked.
Please consider to do so in the next release.
The makefiles already have these option so its not to hard to do so.
to build obsidiand staticaly, just define the variable STATIC=1 in the makefile, or set LMODE=static. To build obsidian-qt staticaly just call qmake with **qmake "RELEASE=1"**.
This way the produced binarys will be staticaly build and a lot of pain would be prevented.

**Comment by netsfx** [comment]
build-new.sh does the job now!
