### ISSUE TITLE
Windows wallet not connecting

### ISSUE THREAD

**Issue by michaeldeblok** [obsidianproject/Obsidian-Qt#8]
![image](https://user-images.githubusercontent.com/20252351/29897207-cebb547a-8dad-11e7-9cee-7d67090d2090.png)

**Comment by Jimmar** [comment]
start wallet -> help -> debug window -> `addnode 104.45.21.229 add` -> wait for connection and sync 

to mine -> `setgenerate true -1`
or you can put any number instead of -1 to use that amount of cores

**Comment by suspended** [comment]
Make sure that it is NOT out of sync before mining. Otherwise you will end up mining your own chain
